# Generated by Django 4.2.16 on 2024-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_direction', models.CharField(choices=[('de_to_en', 'German to English'), ('en_to_de', 'English to German')], max_length=10)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('suggested_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
