# Generated by Django 4.2.16 on 2024-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_translationsession_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationsession',
            name='language_direction',
        ),
        migrations.AddField(
            model_name='translationsession',
            name='buddy_language',
            field=models.CharField(choices=[('de_to_en', 'German to English'), ('en_to_de', 'English to German')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='translationsession',
            name='preferred_language',
            field=models.CharField(choices=[('de_to_en', 'German to English'), ('en_to_de', 'English to German')], default='', max_length=10),
        ),
    ]
