# Generated by Django 4.2.16 on 2024-12-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizMemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memes/')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('meme_choices', models.ManyToManyField(related_name='questions', to='personality_quiz.quizmememodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.CharField(max_length=255)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality_quiz.quizmememodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality_quiz.quizquestionmodel')),
            ],
        ),
    ]
